# Generated by Django 4.0.1 on 2022-04-05 15:07

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_author_alter_book_house_alter_book_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='store.category'),
        ),
    ]
