# Generated by Django 4.0.1 on 2022-04-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_userbookrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='house',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(default='series', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookPublishingHouse',
        ),
        migrations.DeleteModel(
            name='BookSeries',
        ),
    ]
