# Generated by Django 4.0.1 on 2022-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_book_house_alter_book_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='house',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
