# Generated by Django 4.0.1 on 2022-04-09 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_book_house_alter_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(through='store.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
